from setuptools import setup, find_packages

setup(
    name                          = "pyflashdb",
    version                       = "1.0.4",
    author                        = "Aman Singh",
    __credits__ = "Inspired by Komal Verma",
    description                   = "Unified database interface for MySQL, PostgreSQL, and MongoDB.",
    long_description              = open("README.md", encoding="utf-8").read(),
    long_description_content_type = "text/markdown",
    url                           = "https://github.com/AmanDev17/pyflashdb",
    packages                      = find_packages(exclude=["tests*"]),
    python_requires               = ">=3.8",
    install_requires              = [],
    extras_require                = {
        "mysql":    ["mysql-connector-python>=8.0"],
        "postgres": ["psycopg2-binary>=2.9"],
        "mongodb":  ["pymongo>=4.0"],
        "all": [
            "mysql-connector-python>=8.0",
            "psycopg2-binary>=2.9",
            "pymongo>=4.0",
        ],
    },
    classifiers = [
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Database",
        "Topic :: Software Development :: Libraries :: Python Modules",
    ],
    keywords = "database mysql postgresql mongodb crud orm flash unified pyflashdb",
)